#!/bin/sh
echo Copying authorization key...
cp carbonyl_rsa ~/.ssh && chmod 600 ~/.ssh/carbonyl_rsa
echo Installing qterminal if not already installed...
[ -x "$(command -v qterminal)" ] || sudo apt install qterminal || sudo zypper install qterminal || sudo dnf install qterminal || sudo pacman -S qterminal || sudo port install qterminal || { echo Please install qterminal package manually; exit 1; }
echo Installing mosh if not already installed...
[ -x "$(command -v mosh)" ] || sudo apt install mosh || sudo zypper install mosh || sudo dnf install mosh || sudo pacman -S mosh || sudo port install mosh || echo Please install mosh package manually, otherwise we will fall back to compressed SSH
echo Configurating qterminal...
mkdir -p ~/.config/qterminal.org ~/.icons ~/.local/share/applications
cp qterminal.ini ~/.config/qterminal.org/
cp carbonyl.png ~/.icons/
echo Installing desktop file...
desktop-file-install --dir=$HOME/.local/share/applications carbonyl-terminal.desktop && update-desktop-database ~/.local/share/applications
echo Done!